/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:724a412e-9b46-4763-bd97-05431af65c9a",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_Ykmtt1gBx",
  aws_user_pools_web_client_id: "4m3biagqbk4h2k2as8bd823vbo",
  oauth: {
    domain:
      "bistuygulamab53153ec-b53153ec-dev.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "exp://172.20.10.2:8081/",
    redirectSignOut: "exp://172.20.10.2:8081/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://kc3yd336uvaazmxyfzokvycbje.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-d5hv4vd23vfqrmegogr6j33hle",
};

export default awsmobile;
